name: Java CI with docker-test1

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        image: arjunlakshmanasamy/sample-springboot-java
        tag: v3
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
