name: New Build and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag arjunlakshmanasamy/sample-springboot-java:v3
    
    - name: docker login
      env:
        DOCKER_USER:  ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
 
    - name: push the docker image
      run: docker push arjunlakshmanasamy/sample-springboot-java:v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag arjunlakshmanasamy/hello-world-spring-boot:v3
      
    #- name: github login
     # env:
       # username: ${{ github.repository_owner }}
       # password: ${{ secrets.GHCR_TOKEN }}
    #  run: |
        #docker login -u github.repository_owner -p $password 
    
    - name: push the docker image    
      run: docker push ghcr.io/arjunlakshmanasamy/hello-world-spring-boot:v3      
